# Generated by Django 5.0.2 on 2024-02-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_to_question', models.TextField(null=True)),
                ('for_problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_problem', to='web.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.CharField(choices=[('PIL', 'Pill'), ('CIG', 'Cigar/Cigarette'), ('CHE', 'Chewable')], default='PIL', max_length=3)),
                ('quantity', models.IntegerField()),
                ('for_problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_issue', to='web.problem')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.TextField()),
                ('milligrams', models.IntegerField()),
                ('for_solution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solution', to='web.solution')),
            ],
        ),
    ]
