# Generated by Django 5.0.2 on 2024-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
