# Generated by Django 5.0.2 on 2024-02-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_problem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.UUIDField(null=True),
        ),
    ]
