# Generated by Django 5.0.2 on 2024-02-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_questions_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='sol_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('PIL', 'Pill'), ('CIG', 'Cigar/Cigarette'), ('CHE', 'Chewable'), ('LOT', 'Lotion')], default='PIL', max_length=3),
        ),
    ]
