# Generated by Django 5.0.2 on 2024-02-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_ingredientsordered_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
